/* Güvenirlik Laboratuvarı: bütün arayüz metinleri, formül TeX kaynakları,
 * kontrol soruları, yanıt anahtarları ve TGA kartları. Etkileşimli ve durağan
 * sürüm bu tek dosyadan üretilir. Kavramsal cümlelerin iddia kimlikleri (c:)
 * CLAIMS.md ile eşleşir. Uzun tire kullanılmaz. */
(function (root) {
  'use strict';
  const H = (cls, tex) => '\\htmlClass{' + cls + '}{' + tex + '}';

  // ---------------------------------------------------------------------------
  // Formüller: TeX, \htmlClass sarmalayıcıları kaldırılınca formulas.expected.json ile aynıdır (B11)
  // ---------------------------------------------------------------------------
  const F = {
    'm1.varyans': { tex: 's_X^2=\\frac{1}{' + H('t-sd', 'n-1') + '}' + H('t-toplam', '\\sum_p') + ' ' + H('t-kare', '(' + H('t-sapma', 'X_p-\\bar X') + ')^2'), okuma: 'Varyans, her puanın ortalamadan uzaklığının karelerinin toplamının serbestlik derecesine bölümüdür.' },
    'm1.varyans_n': { tex: '\\hat\\sigma_X^2=\\frac{1}{n}\\sum_p (X_p-\\bar X)^2', okuma: 'n paydalı sürüm: kareler toplamı kişi sayısına bölünür.' },
    'm1.kovaryans': { tex: 's_{X_1X_2}=\\frac{1}{n-1}' + H('t-toplam', '\\sum_p') + ' ' + H('t-dikdortgen', '(X_{1p}-\\bar X_1)(X_{2p}-\\bar X_2)'), okuma: 'Kovaryans, iki testteki sapmaların çarpımlarının, yani dikdörtgen alanlarının toplamının serbestlik derecesine bölümüdür.' },
    'm1.korelasyon': { tex: 'r=\\dfrac{' + H('t-kov', 's_{X_1X_2}') + '}{' + H('t-sd2', 's_{X_1}s_{X_2}') + '}=\\dfrac{1}{n-1}\\sum_p z_{1p}z_{2p}', okuma: 'Korelasyon, kovaryansın iki standart sapmanın çarpımına bölümüdür; z puanlarının çarpımlarının ortalamasına eşittir.' },
    'm1.z_puani': { tex: 'z_{1p}=\\dfrac{X_{1p}-\\bar X_1}{s_{X_1}}', okuma: 'z puanı, sapmanın standart sapmaya bölümüdür.' },
    'm2.baslik': { tex: 'X=T+E', okuma: 'Gözlenen puan, gerçek puan ile hata puanının toplamıdır.' },
    'm2.sembol_toplam': { tex: '\\sum', okuma: 'topla' },
    'm2.sembol_ortalama': { tex: '\\bar X', okuma: 'ortalama' },
    'm2.sembol_olcme': { tex: 'X_{pj}', okuma: 'p kişisinin j. ölçmesi' },
    'm2.sembol_madde': { tex: 'X_{pi}', okuma: 'p kişisinin i. maddesi' },
    'm2.sembol_beklenen_deger': { tex: '\\mathbb E', okuma: 'sonsuz tekrardaki ortalama' },
    'm2.sembol_tanim_geregi': { tex: '\\equiv', okuma: 'tanım gereği eşittir' },
    'm2.sembol_kisi_icin': { tex: '\\mid p', okuma: 'p kişisi için' },
    'm2.sembol_sapka': { tex: '\\hat T', okuma: 'şapka: kestirim' },
    'm2.model': { tex: H('t-gozlenen', 'X_{pj}') + '=' + H('t-gercek', 'T_p') + '+' + H('t-hata', 'E_{pj}'), okuma: 'p kişisinin j. ölçmesi, gerçek puanı ile o ölçmedeki hatanın toplamıdır.' },
    'm2.gercek_puan': { tex: H('t-gercek', 'T_p') + '\\equiv\\mathbb E_j(X_{pj})', okuma: 'Gerçek puan, tanım gereği sonsuz tekrardaki ortalamadır.' },
    'm2.hata_ortalamasi': { tex: '\\mathbb E(' + H('t-hata', 'E_{pj}') + '\\mid p)=0', okuma: 'Bir kişinin hatalarının sonsuz tekrardaki ortalaması sıfırdır.' },
    'm2.artik': { tex: '\\hat E_j=X_j-\\hat T', okuma: 'Kestirilmiş artık, ölçmeden kestirilen gerçek puanın çıkarılmasıdır.' },
    'm3.varyans_ayrisimi': { tex: H('t-gozlenen', '\\sigma_X^2') + '=' + H('t-gercek', '\\sigma_T^2') + '+' + H('t-hata', '\\sigma_E^2') + '+' + H('t-ustu-cizili', '2\\sigma_{TE}'), okuma: 'Gözlenen varyans, gerçek varyans ile hata varyansının toplamıdır; kovaryans terimi model gereği sıfırdır.' },
    'm3.rho_oran': { tex: '\\rho_{XX\'}=\\dfrac{' + H('t-gercek', '\\sigma_T^2') + '}{' + H('t-gozlenen', '\\sigma_X^2') + '}=' + H('t-bir-eksi', '1-') + '\\dfrac{' + H('t-hata', '\\sigma_E^2') + '}{\\sigma_X^2}=\\rho_{XT}^2', okuma: 'Güvenirlik, gerçek puan varyansının gözlenen puan varyansına oranıdır.' },
    'm3.osh': { tex: '\\text{ÖSH}=' + H('t-hata', '\\sigma_E') + '=\\sigma_X\\sqrt{1-\\rho_{XX\'}}', okuma: 'Ölçmenin standart hatası, hata puanlarının standart sapmasıdır.' },
    'm3.grup_turdesligi': { tex: '\\rho_{\\text{yeni}}=1-\\dfrac{\\sigma_X^2(1-\\rho_{XX\'})}{\\sigma_{X,\\text{yeni}}^2}', okuma: 'Hata varyansı aynı kalırsa yeni gruptaki güvenirlik, aynı hata varyansının yeni grubun gözlenen varyansına oranının birden çıkarılmasıdır.' },
    'm3.rho_xt_karekok': { tex: '\\rho_{XT}=\\sqrt{\\rho_{XX\'}}', okuma: 'Gözlenen puanın gerçek puanla korelasyonu güvenirliğin kareköküdür.' },
    'm3.hata_varyansi_egilim': { tex: '\\sigma_E^2=\\mathbb E_p\\left(\\sigma^2_{E\\mid p}\\right)', okuma: 'Hata varyansı, her öğrencinin kendi tekrarlarındaki yayılımın ortalamasıdır.' },
    'm4.model': { tex: 'X_{pj}=' + H('t-yapi', '\\eta_p') + '+' + H('t-sabit', 'c') + '+' + H('t-yanli', 'B_p') + '+' + H('t-grup', '\\gamma g_p') + '+' + H('t-hata', 'E_{pj}'), okuma: 'Gözlenen puan; yapı puanı, sabit hata, kişiye özgü kararlı yanlılık, alt gruba özgü kayma ve tesadüfi hatanın toplamıdır.' },
    'm4.sistematik_bilesen': { tex: 'U_p=c+B_p+\\gamma g_p', okuma: 'Sistematik bileşen sabit, kişiye özgü ve gruba özgü parçaların toplamıdır.' },
    'm4.ktk_gercek_puan': { tex: H('t-gercek', 'T_p') + '=' + H('t-yapi', '\\eta_p') + '+' + H('t-yanli', 'U_p'), okuma: 'KTK gerçek puanı, yapı puanı ile sistematik bileşenin toplamıdır; KTK ikisini ayıramaz.' },
    'm4.rho': { tex: '\\rho_{XX\'}=\\dfrac{' + H('t-yapi', '\\sigma_\\eta^2') + '+' + H('t-yanli', '\\sigma_U^2+2\\sigma_{\\eta U}') + '}{\\sigma_\\eta^2+\\sigma_U^2+2\\sigma_{\\eta U}+' + H('t-hata', '\\sigma_E^2') + '}', okuma: 'Güvenirlik, yapı ve kararlı yanlılıktan gelen varyansın, buna hata varyansı eklenmiş toplama oranıdır.' },
    'm4.rho_x_eta': { tex: '\\rho_{X\\eta}=\\dfrac{\\sigma_\\eta^2+\\sigma_{\\eta U}}{\\sigma_X\\,\\sigma_\\eta}', okuma: 'Yapıyla korelasyon, yalnızca simülasyonda hesaplanabilir.' },
    'm4.tavan': { tex: '\\sqrt{\\rho_{XX\'}}', okuma: 'Yapıyla korelasyonun tavanı güvenirliğin kareköküdür.' },
    'm4.sabit_cebir': { tex: '(X_p+' + H('t-sabit', 'c') + ')-(\\bar X+' + H('t-sabit', 'c') + ')=X_p-\\bar X', okuma: 'Herkese eklenen sabit, sapmada birbirini götürür.' },
    'm4.dogrusal_donusum': { tex: 'X^*=a+wX', okuma: 'Ortak doğrusal dönüşüm.' },
    'm4.osh_dogrusal': { tex: '\\text{ÖSH}^*=|w|\\,\\text{ÖSH}', okuma: 'Dönüşümden sonra ölçmenin standart hatası w\'nin mutlak değeri katına çıkar.' },
    'm4.orantili_hata_ornegi': { tex: 'X^*=1{,}1X', okuma: 'Her puan yüzde on fazla sayılıyor.' },
    'm4.yanlilik_dusurme_kosulu': { tex: '\\sigma_U^2+2\\sigma_{\\eta U}<0', okuma: 'Kararlı yanlılık bu koşulda güvenirliği düşürür.' },
    'm4.tavan_esitsizligi': { tex: '\\rho_{XY}\\le\\sqrt{\\rho_{XX\'}\\rho_{YY\'}}', okuma: 'İki ölçmenin korelasyonu güvenirliklerinin geometrik ortalamasını aşamaz.' },
    'm4.zayiflama_duzeltmesi': { tex: '\\rho_{T_XT_Y}=\\rho_{XY}/\\sqrt{\\rho_{XX\'}\\rho_{YY\'}}', okuma: 'Zayıflama düzeltmesi.' },
    'm4.icc_a_1': { tex: '\\text{ICC}(A,1)=\\dfrac{\\hat\\sigma_p^2}{\\hat\\sigma_p^2+\\hat\\sigma_i^2+\\hat\\sigma^2_{pi,e}}', okuma: 'Mutlak uyum; ölçmeler arasındaki sabit kayma da hataya girer.' },
    'm5.fark': { tex: H('t-fark', 'D_p') + '=X_{1p}-X_{2p}=(' + H('t-gercek', 'T_{1p}-T_{2p}') + ')+(' + H('t-hata', 'E_{1p}-E_{2p}') + ')', okuma: 'İki ölçme arasındaki fark, gerçek puan farkı ile hata farkının toplamıdır.' },
    'm5.fark_varyansi_tau': { tex: '\\sigma_D^2=\\sigma^2_{E_1}+\\sigma^2_{E_2}', okuma: 'Farkların varyansı iki hata varyansının toplamıdır.' },
    'm5.fark_varyansi_paralel': { tex: '\\sigma_D^2=2\\sigma_E^2', okuma: 'Paralel ölçmelerde farkların varyansı hata varyansının iki katıdır.' },
    'm5.hata_fark_yolu': { tex: H('t-hata', '\\hat\\sigma_E^2') + '=\\tfrac12 ' + H('t-fark', 's_D^2'), okuma: 'Hata varyansı, farkların varyansının yarısıyla kestirilir.' },
    'm5.kovaryans': { tex: '\\sigma_{X_1X_2}=\\sigma_T^2+\\sigma_{TE_2}+\\sigma_{E_1T}+\\sigma_{E_1E_2}=' + H('t-gercek', '\\sigma_T^2'), okuma: 'İki paralel ölçmenin kovaryansı gerçek puan varyansına eşittir; diğer terimler model gereği sıfırdır.' },
    'm5.hata_kovaryans_yolu': { tex: '\\hat\\sigma_E^2=s_X^2(1-r_{12})', okuma: 'Hata varyansı, gözlenen varyansın korelasyonla açıklanmayan kısmıdır.' },
    'm5.ortalama_varyans': { tex: '\\bar s_X^2=(s^2_{X_1}+s^2_{X_2})/2', okuma: 'İki formun ortalama varyansı.' },
    'm5.fark_yolu_orani': { tex: '1-\\hat\\sigma_E^2/\\bar s_X^2', okuma: 'Fark yolundan güvenirlik.' },
    'm5.esit_olmayan_hata_r': { tex: 'r=\\sqrt{\\rho_1\\rho_2}', okuma: 'Hata varyansları eşit değilse korelasyon iki güvenirliğin geometrik ortalamasıdır.' },
    'm5.osh_bandi': { tex: 'X\\pm1{,}96\\,\\text{ÖSH}', okuma: 'Gözlenen puanın iki yanında bir virgül doksan altı ölçmenin standart hatası kadar bant.' },
    'm5.kelley': { tex: '\\hat T=\\rho X+(1-\\rho)\\mu_X', okuma: 'Kelley kestirimi gözlenen puanı grup ortalamasına doğru çeker.' },
    'm5.kelley_bandi': { tex: '\\hat T\\pm1{,}96\\,\\sigma_X\\sqrt{\\rho(1-\\rho)}', okuma: 'Kelley bandı kestirimin standart hatasıyla kurulur.' },
    'm5.uc_standart_hata': { tex: '\\text{ölçme: }\\sigma_X\\sqrt{1-\\rho},\\ \\ \\text{kestirim: }\\sigma_X\\sqrt{\\rho(1-\\rho)},\\ \\ \\text{yordama: }\\sigma_X\\sqrt{1-\\rho^2}', okuma: 'Üç farklı standart hata üç farklı soruyu yanıtlar.' },
    'm5.kosullu_osh': { tex: '\\text{ÖSH}(x)=\\sqrt{x(k-x)/(k-1)}', okuma: 'Lord\'un koşullu ölçmenin standart hatası.' },
    'm5.binom_hata_varyansi': { tex: 'k\\zeta(1-\\zeta)', okuma: 'Binom modelde hata varyansı gerçek düzeye bağlıdır.' },
    'm6.rho_tekrar': { tex: '\\rho_{\\text{tekrar}}=\\frac{\\sigma_p^2+' + H('t-madde', '\\sigma_{pi}^2/k') + '}{\\sigma_p^2+\\sigma_{pi}^2/k+' + H('t-gun', '\\sigma_{po}^2') + '+\\sigma_e^2/k}', okuma: 'Test-tekrar testte maddeye özgü sapmalar gerçek puana, güne özgü sapmalar hataya katılır.' },
    'm6.rho_esdeger': { tex: '\\rho_{\\text{eşdeğer}}=\\frac{\\sigma_p^2+' + H('t-gun', '\\sigma_{po}^2') + '}{\\sigma_p^2+\\sigma_{po}^2+(' + H('t-madde', '\\sigma_{pi}^2') + '+\\sigma_e^2)/k}', okuma: 'Eşdeğer formlarda güne özgü sapmalar gerçek puana, maddeye özgü sapmalar hataya katılır.' },
    'm6.rho_gecikmeli_esdeger': { tex: '\\rho_{\\text{gecikmeli eşdeğer}}=\\frac{\\sigma_p^2}{\\sigma_p^2+' + H('t-gun', '\\sigma_{po}^2') + '+(' + H('t-madde', '\\sigma_{pi}^2') + '+\\sigma_e^2)/k}', okuma: 'Gecikmeli eşdeğer formlarda hem güne hem maddeye özgü sapmalar hataya katılır.' },
    'm7.r_sapma': { tex: 'r=\\dfrac{' + H('t-dikdortgen', '\\sum x_1x_2') + '}{\\sqrt{' + H('t-kare', '\\sum x_1^2\\sum x_2^2') + '}}', okuma: 'Korelasyon, sapma çarpımları toplamının sapma kareleri toplamlarının çarpımının kareköküne bölümüdür.' },
    'm7.sapma': { tex: 'x=X-\\bar X', okuma: 'Küçük harf sapmadır.' },
    'm7.sb': { tex: '\\rho_m=\\dfrac{m\\rho}{1+(m-1)\\rho}', okuma: 'Spearman-Brown: test m katına çıkarılınca güvenirlik.' },
    'm7.sb_carpan': { tex: 'm=\\dfrac{\\rho^*(1-\\rho)}{\\rho(1-\\rho^*)}', okuma: 'Hedef güvenirliğe ulaşmak için gereken uzunluk çarpanı.' },
    'm7.sb_yarilar': { tex: '\\rho_{SB}=\\dfrac{2r_{hh}}{1+r_{hh}}', okuma: 'Yarı test korelasyonundan tam test güvenirliği.' },
    'm7.flanagan_rulon': { tex: '2\\left(1-\\dfrac{s_A^2+s_B^2}{s_Y^2}\\right)', okuma: 'Flanagan-Rulon katsayısı.' },
    'm7.rulon': { tex: '1-\\dfrac{s_D^2}{s_Y^2}', okuma: 'Rulon katsayısı: yarılar arasındaki fark varyansının toplam varyansa oranının birden çıkarılması.' },
    'm7.rulon_fark': { tex: 'D=A-B', okuma: 'Yarılar arasındaki fark.' },
    'm7.fr_ortalama_k_tek': { tex: '\\alpha\\,(k^2-1)/k^2', okuma: 'k tekken bölmelerin Flanagan-Rulon ortalaması.' },
    'm7.alpha': { tex: '\\hat\\alpha=\\dfrac{' + H('t-carpan', 'k') + '}{' + H('t-carpan', 'k-1') + '}\\left(1-\\dfrac{' + H('t-madde-var', '\\sum_i s_i^2') + '}{' + H('t-toplam-var', 's_Y^2') + '}\\right)', okuma: 'Alfa, madde varyansları toplamının toplam puan varyansına oranının birden çıkarılıp k bölü k eksi bir ile çarpılmasıdır.' },
    'm7.toplam_varyans_n': { tex: '\\hat\\sigma_Y^2=\\frac1n\\sum_p(Y_p-\\bar Y)^2', okuma: 'n paydalı toplam puan varyansı.' },
    'm7.kr20': { tex: '\\text{KR-20}=\\dfrac{k}{k-1}\\left(1-\\dfrac{' + H('t-madde-var', '\\sum_i p_iq_i') + '}{' + H('t-toplam-var', '\\hat\\sigma_Y^2') + '}\\right)', okuma: 'KR-20, doğru-yanlış puanlanan maddelerde alfanın özel durumudur.' },
    'm7.kr20_pq_duzeltmesi': { tex: 'p_iq_i\\cdot n/(n-1)', okuma: 'n eksi bir paydasında madde varyansı.' },
    'm7.kr21': { tex: '\\text{KR-21}=\\dfrac{k}{k-1}\\left(1-\\dfrac{M(k-M)}{k\\,\\hat\\sigma_Y^2}\\right)', okuma: 'KR-21 eşit madde güçlüğü varsayar.' },
    'm7.osh_orneklem': { tex: 's_Y\\sqrt{1-\\hat\\alpha}', okuma: 'Örneklem ölçmenin standart hatası.' },
    'm7.madde_varyansi_egrisi': { tex: 'p(1-p)', okuma: 'Doğru-yanlış maddenin varyansı.' },
    'm7.alpha_madde_silinirse': { tex: '\\hat\\alpha_{(-i)}=\\dfrac{k-1}{k-2}\\left(1-\\dfrac{\\sum_{j\\neq i}s_j^2}{s^2_{Y-X_i}}\\right)', okuma: 'Madde silinirse alfa.' },
    'm7.duzeltilmis_madde_toplam_r': { tex: 'r_{X_i(Y-X_i)}=\\dfrac{s_{X_iY}-s_i^2}{s_i\\sqrt{s_Y^2+s_i^2-2s_{X_iY}}}', okuma: 'Düzeltilmiş madde-toplam korelasyonu.' },
    'm7.max_rphi': { tex: '\\max r_\\varphi=\\sqrt{\\dfrac{p_i(1-p_j)}{p_j(1-p_i)}}', okuma: 'İki madde arasındaki en büyük fi katsayısı.' },
    'm7.max_rphi_kosulu': { tex: 'p_i\\le p_j', okuma: '' },
    'm8.toplam_varyans': { tex: '\\sigma_Y^2=\\mathbf 1^{\\mathsf T}\\Sigma\\mathbf 1=' + H('t-kosegen', '\\operatorname{tr}(\\Sigma)') + '+' + H('t-kosegen-disi', '\\sum_{i\\neq j}\\sigma_{ij}'), okuma: 'Toplam puan varyansı, kovaryans matrisinin bütün hücrelerinin toplamıdır.' },
    'm8.alpha': { tex: '\\alpha=\\frac{k}{k-1}\\left(1-\\frac{' + H('t-kosegen', '\\operatorname{tr}\\Sigma') + '}{\\mathbf 1^{\\mathsf T}\\Sigma\\mathbf 1}\\right)=\\frac{' + H('t-kosegen-disi', 'k^2\\bar\\sigma_{ij}') + '}{\\mathbf 1^{\\mathsf T}\\Sigma\\mathbf 1}', okuma: 'Alfa, ortalama köşegen dışı kovaryansın k kare katının toplam varyansa oranıdır.' },
    'm8.turetme_ortalama_kovaryans': { tex: '\\bar\\sigma_{ij}=\\sum_{i\\neq j}\\sigma_{ij}/[k(k-1)]', okuma: 'Ortalama köşegen dışı kovaryans.' },
    'm8.turetme_gercek_varyans': { tex: '\\approx k^2\\bar\\sigma_{ij}', okuma: 'Toplamın gerçek varyansı yaklaşık olarak bu değerdir.' },
    'm8.turetme_alpha': { tex: '\\alpha=k^2\\bar\\sigma_{ij}/\\sigma_Y^2', okuma: '' },
    'm8.sigma_ayrisimi': { tex: '\\Sigma=' + H('t-gercek', '\\Sigma_T') + '+' + H('t-hata', '\\Sigma_E'), okuma: 'Kovaryans matrisi gerçek puan ve hata matrislerinin toplamıdır.' },
    'm8.hata_matrisi': { tex: '\\Sigma_E=\\Psi', okuma: '' },
    'm8.tek_faktor': { tex: '\\Sigma=\\lambda\\lambda^{\\mathsf T}+\\Psi', okuma: 'Tek faktör modeli.' },
    'm8.omega': { tex: '\\omega=\\dfrac{(\\sum_i\\lambda_i)^2}{\\mathbf 1^{\\mathsf T}\\Sigma\\mathbf 1}', okuma: 'Omega, ortak faktörün toplam varyanstaki payıdır.' },
    'm8.omega_paydasi_iliskisiz': { tex: '(\\sum\\lambda_i)^2+\\sum\\psi_i', okuma: '' },
    'm8.alpha_yukler': { tex: '\\alpha=\\dfrac{k}{k-1}\\cdot\\dfrac{(\\sum\\lambda)^2-\\sum\\lambda^2}{\\sigma_Y^2}\\le\\omega', okuma: 'Hatalar ilişkisizken alfa omegayı aşamaz.' },
    'm8.yuk_esitsizligi': { tex: '(\\sum\\lambda)^2\\le k\\sum\\lambda^2', okuma: '' },
    'm8.alpha_std': { tex: '\\alpha_{std}=\\dfrac{k\\bar r}{1+(k-1)\\bar r}', okuma: 'Standart alfa, ortalama madde korelasyonuna uygulanmış Spearman-Brown formülüdür.' },
    'm8.l2': { tex: 'L_2=\\dfrac{\\sum_{i\\neq j}\\sigma_{ij}+\\sqrt{\\frac{k}{k-1}\\sum_{i\\neq j}\\sigma_{ij}^2}}{\\sigma_Y^2}\\ge\\alpha', okuma: 'Guttman L iki katsayısı alfadan küçük olamaz.' },
    'm8.iki_blok_orani': { tex: '\\mathbf 1^{\\mathsf T}\\Sigma_T\\mathbf 1/\\mathbf 1^{\\mathsf T}\\Sigma\\mathbf 1', okuma: 'Toplamın gerçek varyans payı.' },
    'm8.psi_varsayilan': { tex: '\\psi_i=1-\\lambda_i^2', okuma: '' },
    'm8.psi_siniri': { tex: '|\\psi_{ij}|\\le0{,}9\\sqrt{\\psi_i\\psi_j}', okuma: '' },
    'm9.model': { tex: 'X_{pi}=\\mu+' + H('t-kisi', '\\nu_p') + '+' + H('t-madde', '\\nu_i') + '+' + H('t-artik', '\\nu_{pi,e}'), okuma: 'Her hücre; genel ortalama, kişi etkisi, madde etkisi ve artığın toplamıdır.' },
    'm9.kt_ayrisimi': { tex: 'KT_T=' + H('t-kisi', 'KT_p') + '+' + H('t-madde', 'KT_i') + '+' + H('t-artik', 'KT_{art}'), okuma: 'Toplam kareler toplamı kişi, madde ve artık kareler toplamlarına ayrılır.' },
    'm9.kt_kisi': { tex: 'KT_p=k\\sum_p(\\bar X_{p\\cdot}-\\bar X)^2', okuma: '' },
    'm9.kt_madde': { tex: 'KT_i=n\\sum_i(\\bar X_{\\cdot i}-\\bar X)^2', okuma: '' },
    'm9.kt_artik': { tex: 'KT_{art}=\\sum_p\\sum_i(X_{pi}-\\bar X_{p\\cdot}-\\bar X_{\\cdot i}+\\bar X)^2', okuma: '' },
    'm9.sd_kisi': { tex: 'n-1', okuma: '' }, 'm9.sd_madde': { tex: 'k-1', okuma: '' }, 'm9.sd_artik': { tex: '(n-1)(k-1)', okuma: '' },
    'm9.hoyt': { tex: 'r_H=1-\\dfrac{' + H('t-artik', 'KO_{art}') + '}{' + H('t-kisi', 'KO_p') + '}', okuma: 'Hoyt katsayısı, artık kareler ortalamasının kişi kareler ortalamasına oranının birden çıkarılmasıdır.' },
    'm9.kanit_toplam_varyans': { tex: 's_Y^2=k\\,KO_p', okuma: '' },
    'm9.kanit_madde_varyanslari': { tex: '\\sum_i s_i^2=\\dfrac{KT_p+KT_{art}}{n-1}', okuma: '' },
    'm9.kanit_alpha_hoyt': { tex: '\\hat\\alpha=\\dfrac{k}{k-1}\\left(1-\\dfrac{KT_p+KT_{art}}{k\\,KT_p}\\right)=1-\\dfrac{KO_{art}}{KO_p}', okuma: 'Alfa ile Hoyt katsayısı cebirsel olarak aynıdır.' },
    'm9.beklenen_ko_kisi': { tex: '\\mathbb E(KO_p)=\\sigma^2_{pi,e}+n_i\\sigma_p^2', okuma: '' },
    'm9.beklenen_ko_madde': { tex: '\\mathbb E(KO_i)=\\sigma^2_{pi,e}+n_p\\sigma_i^2', okuma: '' },
    'm9.beklenen_ko_artik': { tex: '\\mathbb E(KO_{art})=\\sigma^2_{pi,e}', okuma: '' },
    'm9.bilesen_kisi': { tex: '\\hat\\sigma_p^2=(KO_p-KO_{art})/n_i', okuma: '' },
    'm9.bilesen_madde': { tex: '\\hat\\sigma_i^2=(KO_i-KO_{art})/n_p', okuma: '' },
    'm9.bilesen_artik': { tex: '\\hat\\sigma^2_{pi,e}=KO_{art}', okuma: '' },
    'm9.erho2': { tex: '\\mathbb E\\rho^2=\\dfrac{' + H('t-kisi', '\\sigma_p^2') + '}{\\sigma_p^2+' + H('t-artik', '\\sigma^2_{pi,e}/n_i\'') + '}', okuma: 'G katsayısı: bağıl kararlar için güvenirlik.' },
    'm9.phi': { tex: '\\Phi=\\dfrac{' + H('t-kisi', '\\sigma_p^2') + '}{\\sigma_p^2+(' + H('t-madde', '\\sigma_i^2') + '+' + H('t-artik', '\\sigma^2_{pi,e}') + ')/n_i\'}', okuma: 'Mutlak kararlar için Phi katsayısı; madde güçlüğü farkları da hataya girer.' },
    'm9.phi_lambda': { tex: '\\Phi(\\lambda)=\\dfrac{\\sigma_p^2+(\\mu-\\lambda)^2}{\\sigma_p^2+(\\mu-\\lambda)^2+\\sigma^2_\\Delta}', okuma: 'Kesme puanına özgü Phi.' },
    'm9.phi_en_kucuk': { tex: '\\Phi=\\min_\\lambda\\Phi(\\lambda)=\\Phi(\\mu)', okuma: '' },
    'm9.capraz_bagil_hata': { tex: '\\sigma^2_\\delta=\\sigma^2_{pr,e}/n_r\'', okuma: '' },
    'm9.capraz_mutlak_hata': { tex: '\\sigma^2_\\Delta=(\\sigma^2_r+\\sigma^2_{pr,e})/n_r\'', okuma: '' },
    'm9.icice_hata': { tex: '\\sigma^2_\\delta=\\sigma^2_\\Delta=\\sigma^2_{r,pr,e}/n_r\'', okuma: 'İç içe desende puanlayıcı katılığı bağıl hataya da girer.' },
    'm9.icice_bilesen': { tex: '\\sigma^2_{r,pr,e}=\\sigma_r^2+\\sigma^2_{pr,e}', okuma: '' },
    'm9.icc_a_k': { tex: '=\\dfrac{KO_p-KO_{art}}{KO_p+(KO_i-KO_{art})/n}', okuma: '' },
    'm9.icc_c_1': { tex: '=\\dfrac{KO_p-KO_{art}}{KO_p+(k-1)KO_{art}}', okuma: '' },
    'm9.icc_c_k': { tex: '\\alpha=\\text{ICC}(C,k)=\\text{ICC}(3,k)', okuma: '' },
    'm9.icc_a_k_tam': { tex: '\\Phi=\\text{ICC}(A,k)=\\text{ICC}(2,k)=\\dfrac{KO_p-KO_{art}}{KO_p+(KO_i-KO_{art})/n}', okuma: '' },
    'm9.icc_c_1_tam': { tex: '\\mathbb E\\rho^2(n_i\'=1)=\\text{ICC}(C,1)=\\dfrac{KO_p-KO_{art}}{KO_p+(k-1)KO_{art}}', okuma: '' },
    'm9.icice_tek_yonlu_not': { tex: 'KO_{\\text{içi}}=7/6,\\quad \\hat\\sigma_p^2=23/24,\\quad \\mathbb E\\rho^2=\\Phi=\\text{ICC}(1,k)=23/30\\approx0{,}7667', okuma: '' },
    'm9.uc_yol_matris': { tex: 's_Y^2-k^2\\bar s_{ij}=20-16=4', okuma: 'Matris yolu.' },
    'm9.uc_yol_anova': { tex: 'k\\cdot KO_{art}=4\\cdot1=4', okuma: 'ANOVA yolu.' },
    'm9.uc_yol_katsayi': { tex: 's_Y^2(1-\\hat\\alpha)=20\\cdot0{,}2=4', okuma: 'Katsayı yolu.' },
    'm9.uc_yol_kosegen': { tex: '0{,}5+0{,}5+2{,}1+0{,}9=4', okuma: 'Köşegen doldurma yolu.' },
    'ortak.payda_n_eksi_1': { tex: 's^2=\\frac{1}{n-1}\\sum(\\cdot)^2', okuma: '' },
    'ortak.payda_n': { tex: '\\hat\\sigma^2=\\frac{1}{n}\\sum(\\cdot)^2', okuma: '' },
    'ortak.toplam_puan': { tex: 'Y_p=\\sum_i X_{pi}', okuma: 'Toplam puan madde puanlarının toplamıdır.' },
    'icerik.a5_paralel': { tex: 'T_i=\\tau', okuma: '' },
    'icerik.a5_ozunde_tau_esdeger': { tex: 'T_i=\\tau+\\beta_i', okuma: '' },
    'icerik.a5_konjenerik': { tex: 'T_i=\\beta_i+\\lambda_i\\tau', okuma: '' },
    'icerik.c1_fark_varyansi': { tex: '\\sigma^2_{X-X\'}=2\\sigma_E^2', okuma: '' },
    'icerik.d7_esitsizlik': { tex: '\\rho_{XY}\\le\\sqrt{\\rho_{XX\'}\\rho_{YY\'}}\\le\\sqrt{\\rho_{XX\'}}', okuma: '' },
  };

  // Terim düğmeleri: sınıf → etiket ve görseldeki rol
  const TERMS = {
    't-sapma': 'Sapma (X − ortalama)', 't-kare': 'Sapma karesi', 't-toplam': 'Toplam', 't-sd': 'Serbestlik derecesi',
    't-dikdortgen': 'Sapma çarpımı (dikdörtgen)', 't-kov': 'Kovaryans', 't-sd2': 'Standart sapmalar',
    't-gozlenen': 'Gözlenen (X)', 't-gercek': 'Gerçek (T)', 't-hata': 'Hata (E)', 't-ustu-cizili': '2σ_TE (model gereği 0)', 't-bir-eksi': '1 − hata payı',
    't-yapi': 'Yapı puanı η (yalnızca simülasyonda)', 't-sabit': 'Sabit hata c', 't-yanli': 'Kararlı yanlılık', 't-grup': 'Alt grup kayması',
    't-fark': 'Farklar (D)', 't-madde': 'Madde', 't-gun': 'Gün (geçici)', 't-carpan': 'k/(k−1) çarpanı', 't-madde-var': 'Madde varyansları toplamı', 't-toplam-var': 'Toplam puan varyansı',
    't-kosegen': 'Köşegen (iz)', 't-kosegen-disi': 'Köşegen dışı', 't-kisi': 'Kişi', 't-artik': 'Artık',
  };

  // ---------------------------------------------------------------------------
  // Modüller
  // ---------------------------------------------------------------------------
  const MODULES = [
    {
      id: 'm1', kisa: 'Varyans ve korelasyon', baslik: 'M1. Varyans, kovaryans, korelasyon', dakika: 12,
      kazanimlar: [
        'Varyansı sapma karelerinden hesaplar ve herkese sabit eklemenin varyansı neden değiştirmediğini açıklar (S1, S2; Y3).',
        'Kovaryans ile korelasyonu dikdörtgen alanlarıyla hesaplar ve gürültünün korelasyonu neden düşürdüğünü açıklar (S1, S3).',
      ],
      giris: 'Güvenirliğin bütün formülleri iki işleme dayanır: bir puanın ortalamadan ne kadar uzak olduğu (sapma) ve iki ölçmede bu uzaklıkların birlikte değişmesi (kovaryans). Bu modül bu iki işlemi elle görünür kılar.',
      formuller: ['m1.varyans', 'm1.kovaryans', 'm1.korelasyon'],
      uzmanFormuller: ['m1.varyans_n', 'm1.z_puani'],
      gorulmesi: [
        { t: '"Herkese +10" bütün noktaları kaydırır ama tek bir kareyi değiştirmez; "Herkesi ×2" her kareyi dört katına çıkarır.', c: 'B.5' },
        { t: 'Gürültünün eklediği iki işaretli dikdörtgenler kovaryansta ortalamada birbirini götürür; ama gürültü Test 2\'nin karelerini büyütür, payda artar ve r düşer. Götürme yalnızca ortalamada ve yalnızca kovaryansta olur; tek bir öğrencinin puanında hata götürülmez.', c: 'Y3' },
        { t: 'Sekiz noktadan yedisini sürüklersen sekizincinin sapması kendiliğinden belirlenir, çünkü sapmaların toplamı sıfırdır. Serbestçe değişebilen sapma sayısı n − 1\'dir (serbestlik derecesi, sd).', c: 'M1-Formüller' },
      ],
      kontrol: [
        { soru: 'A sınıfı 40, 50, 60; B sınıfı 70, 80, 90 aldı. Hangisinin varyansı büyük?', yanit: 'Eşit (ikisinde de 100).', anahtar: 'A15.1' },
        { soru: 'A\'da herkese 5 puan eklenirse varyans?', yanit: 'Değişmez.', anahtar: 'A15.2' },
        { soru: 'Tekrar testte herkes tam 5 puan fazla alırsa r?', yanit: 'Puanlar değişkense 1.', anahtar: 'A15.3', sayi: 1 },
        { soru: '5 puan sınıfın rastgele yarısına verilirse?', yanit: 'r < 1.', anahtar: 'A15.4' },
        { soru: 'Test 2\'ye gürültü eklenince kovaryans ve r nasıl değişir?', yanit: 'Kovaryans ortalamada değişmez; r düşer.', anahtar: 'A15.5' },
      ],
    },
    {
      id: 'm2', kisa: 'X = T + E', baslik: 'M2. Bir öğrenci, sonsuz tekrar: X = T + E', dakika: 12,
      kazanimlar: [
        'Gerçek puanı sonsuz tekrarın ortalaması olarak tanımlar ve hatanın ortalamasının neden tanım gereği sıfır olduğunu açıklar (S2).',
        'Kestirilmiş artık ile gerçek hata puanını ayırt eder (S3; Y4).',
      ],
      giris: 'Ayşe aynı testi tekrar tekrar alıyor ve her ölçmeden sonra testi hiç görmemiş gibi oluyor (Lord ve Novick\'in bellek silme düşünce deneyi). Ölçmeleri biriktir ve ortalamanın nereye yerleştiğine bak.',
      formuller: ['m2.model', 'm2.gercek_puan', 'm2.hata_ortalamasi', 'm2.artik'],
      semboller: ['m2.sembol_toplam', 'm2.sembol_ortalama', 'm2.sembol_olcme', 'm2.sembol_madde', 'm2.sembol_beklenen_deger', 'm2.sembol_tanim_geregi', 'm2.sembol_kisi_icin', 'm2.sembol_sapka'],
      gorulmesi: [
        { t: 'Hatanın ortalamasının sıfır olması bir keşif değil, tanımdır. Sonucu: tekrarlar boyunca ortalaması sıfırlanmayan bir sapma, tanım gereği T\'nin parçasıdır.', c: 'A.1' },
        { t: 'Ölçmeden hesaplanan X − T̂ değerleri artıklardır, hata puanları değildir. Gerçek E yalnızca T\'nin bilindiği perde arkasında görünür.', c: 'C.1' },
      ],
      kontrol: [
        { soru: 'Ayşe\'nin tekrarları 62, 58, 65, 55, 60. T̂ ve artıklar?', yanit: 'T̂ = 60; artıklar +2, −2, +5, −5, 0. Bunlar kestirilmiş artıklardır.', anahtar: 'A15.7', sayi: 60 },
        { soru: 'Aynı beş ölçmeyi her seferinde Ayşe\'ye 3 puan fazla veren bir puanlayıcı puanlasaydı T̂ ve artıklar?', yanit: 'T̂ = 63; artıklar değişmez. Her tekrarda aynı kalan fazlalık hataya değil gerçek puana gider. Tekrarlarda puanlayıcı değişseydi bu sapma hata olurdu.', anahtar: 'A15.9', sayi: 63 },
      ],
    },
    {
      id: 'm3', kisa: 'Varyans bütçesi', baslik: 'M3. Sınıf düzeyinde varyans bütçesi ve güvenirlik oranı', dakika: 14,
      kazanimlar: [
        'Güvenirliği gerçek varyansın gözlenen varyansa oranı olarak hesaplar ve bunu bireyler hakkında bir ifade gibi yorumlamaz (S1; Y1, Y8).',
        'Grup türdeşliğinin güvenirliği ve ÖSH\'yi nasıl etkilediğini açıklar (Y1).',
      ],
      giris: 'İki dünya var: kaydırıcılar evrendeki (popülasyon) değerleri σ belirler; bu sınıftaki değerler s ise her yeni sınıfta biraz dalgalanır. "Yeni sınıf çek" düğmesine birkaç kez basıp s değerlerinin σ çevresinde dolaştığını gör.',
      formuller: ['m3.varyans_ayrisimi', 'm3.rho_oran', 'm3.osh', 'm3.grup_turdesligi'],
      uzmanFormuller: ['m3.rho_xt_karekok', 'm3.hata_varyansi_egilim'],
      gorulmesi: [
        { t: 'σ_E sabitken türdeş bir sınıfta güvenirlik düşer, ÖSH değişmez. Güvenirlik testin değil, bu puanların bu gruptaki özelliğidir.', c: 'Y1' },
        { t: 'ρ = 0,80, bu popülasyonda gözlenen varyansın %80\'inin gerçek varyans olduğu demektir; tek tek öğrencilerin puanları hakkında bir ifade değildir.', c: 'Y8' },
        { t: 'Hata varyansı puan düzeyine bağlı değilse ÖSH gruptan gruba güvenirlik katsayısından daha az değişir; bu yüzden ikisi birlikte raporlanır.', c: 'D.5' },
      ],
      kontrol: [
        { soru: 'σ_T² = 64, σ_E² = 16 ise güvenirlik?', yanit: '0,80.', anahtar: 'A15.11', sayi: 0.8 },
        { soru: 'Aynı test, σ_T² = 16?', yanit: '0,50.', anahtar: 'A15.12', sayi: 0.5 },
        { soru: 'ÖSH değişti mi?', yanit: 'Hayır, ikisinde de 4.', anahtar: 'A15.13', sayi: 4 },
      ],
    },
    {
      id: 'm4', kisa: 'Hata Laboratuvarı', baslik: 'M4. Hata Laboratuvarı: sabit, kurala bağlı, kararlı ve tesadüfi hata', dakika: 15,
      kazanimlar: [
        'Sabit, kurala bağlı, kişiye özgü kararlı ve tesadüfi hatanın ortalama, güvenirlik ve yapıyla ilişki üzerindeki etkisini ayırt eder (S2; Y2, Y13, Y16).',
        'Bir hatanın sistematik mi tesadüfi mi sayılacağının tekrar tasarımına bağlı olduğunu örnekle açıklar (S2; Y7).',
      ],
      giris: 'Aynı öğrencileri iki kez ölçüyoruz. Her hata türünü tek tek aç ve üç şeye bak: ortalama, iki ölçme arasındaki korelasyon (güvenirlik) ve puanın yapıyla korelasyonu (yalnızca simülasyonda görülebilir).',
      formuller: ['m4.model', 'm4.ktk_gercek_puan', 'm4.rho', 'm4.rho_x_eta', 'm4.sabit_cebir', 'm4.osh_dogrusal'],
      uzmanFormuller: ['m4.sistematik_bilesen', 'm4.dogrusal_donusum', 'm4.yanlilik_dusurme_kosulu', 'm4.tavan_esitsizligi', 'm4.zayiflama_duzeltmesi', 'm4.icc_a_1'],
      ozet: { t: 'Güvenirlik katsayıları yalnızca ortalamadan sapmalardan kurulur, bu yüzden herkese aynı eklenen sabitler kaybolur. Her tekrarda aynı kişide aynı biçimde yinelenen bir yanlılık, kişiler arasındaki gerçek bir farktan ayırt edilemez; KTK onu gerçek varyans olarak kaydeder ve bedeli yapıyla ilişkiye yansır. Yalnızca tekrarlar arasında değişen hata tekrarlar arasında uyumsuzluk yaratır; bu katsayılar yalnızca uyumsuzluğu görebilir. "Tesadüfi" burada "nedensiz" değil, "bu tasarımdaki tekrarlarda yinelenmeyen" demektir.', c: 'B.3' },
      uzlastirma: { t: '"Sabit ve sistematik hatalar geçerliği, tesadüfi hatalar güvenirliği etkiler" kuralı iki durumda tam olarak doğrudur: hata herkese aynı miktarda eklendiğinde (sabit hata) ya da herkese aynı kuralla uygulandığında (ör. her puanın %10 fazla sayılması) ve bu her tekrarda aynı biçimde olduğunda. Bu iki durumda güvenirlik hiç değişmez; bedel ortalamaya, mutlak kararlara ve puanların mutlak yorumuna yansır. Hata kişiden kişiye değişip tekrarlarda aynı kalıyorsa güvenirliği değiştirir: çoğunlukla yükseltir (senaryo 3 ve 8; Sabit Veri A\'da 0,80\'den 76/91 ≈ 0,84\'e; yanlılık yüksek puanlılara yönelikse 10/11 ≈ 0,91\'e), yapıyla güçlü ters ilişkiliyse düşürür (senaryo 7; 0,80\'den 2/7 ≈ 0,29\'a). Yanlılık yapıyla ilişkisizse puanların yapıyla ilişkisi zayıflar. Hata tekrardan tekrara değişiyorsa, adı ne olursa olsun, bu tasarım için tesadüfi hatadır ve güvenirliği düşürür (senaryo 4). Uygulama kuralı çürütmez; "etkilemez" sözcüğünü koşullarıyla birlikte okur.', c: 'B.0, B.1, B.3', not: 'SPEC satır 173\'teki metin, SPEC_SORULARI madde 3\'teki en küçük düzeltmeyle kullanıldı.' },
      kontrol: [
        { soru: 'Yazılım hatası herkesten 4 puan düşüyor. r, ÖSH, ortalama ve 50 kesme puanındaki kararlar ne olur?', yanit: 'r ve ÖSH aynı; ortalama 4 düşer; kararlar etkilenir.', anahtar: 'A15.48' },
        { soru: 'Aynı puanlayıcı iki ölçmede de düzgün yazılı kâğıtlara 5 puan fazla veriyor. Düzgün yazı yapıyla ilişkisizse ne olur?', yanit: 'Güvenirlik düşmez, yükselir; yapıyla korelasyon düşer.', anahtar: 'A15.52' },
      ],
    },
    {
      id: 'm5', kisa: 'Görünmeyeni kestirmek', baslik: 'M5. Görünmeyeni kestirmek ve ÖSH', dakika: 15,
      kazanimlar: [
        'İki paralel ölçmeden hata varyansını ve ÖSH\'yi fark yolu, kovaryans yolu ve köşegen yoluyla hesaplar ve üçünün aynı sayıya vardığını gösterir (S1, S3; Y4).',
        'ÖSH bandını doğru yorumlar ve varsayımlar bozulunca kestirimin hangi yöne yanlılaştığını söyler (S3; Y9, Y14).',
      ],
      giris: 'Yalnızca puanları görüyorsun. Hataların ortalama büyüklüğünü bilebilir miyiz? Altı öğrenci iki eşdeğer formu aldı: X₁ = 10, 12, 14, 16, 18, 20 ve X₂ = 11, 11, 15, 14, 19, 20.',
      formuller: ['m5.fark', 'm5.hata_fark_yolu', 'm5.kovaryans', 'm5.hata_kovaryans_yolu', 'm5.osh_bandi'],
      uzmanFormuller: ['m5.fark_varyansi_tau', 'm5.fark_varyansi_paralel', 'm5.ortalama_varyans', 'm5.fark_yolu_orani', 'm5.esit_olmayan_hata_r', 'm5.kelley', 'm5.kelley_bandi', 'm5.uc_standart_hata', 'm5.kosullu_osh', 'm5.binom_hata_varyansi'],
      gorulmesi: [
        { t: 'Farkların ortalaması sabit kaymayı, farkların yayılımı tesadüfi hatayı gösterir. Fark yolu ile köşegen yolu aynı sayıyı verir.', c: 'C.2' },
        { t: 'Hatayı hiçbir zaman gözlemeyiz; tekrarlar arasındaki uyumsuzluğu gözler ve bir model altında hatayı çıkarsarız. Anahtarlar o modelin varsayımlarını görünür kılar.', c: 'C.1' },
        { t: 'X ± 1,96 ÖSH için "%95", normal hata varsayımıyla ve bu kişinin koşullu hata standart sapması ÖSH\'ye eşitse, aynı kişinin tekrarlanan ölçmelerinde bu aralıkların yaklaşık %95\'inin gerçek puanı kapsaması demektir. Tek bir aralık için "%95 olasılıkla gerçek puanı içerir" denmez.', c: 'D.5' },
        { t: 'Bellek etkisi (ilişkili hatalar) güvenirliği fazla, gerçek değişim az kestirtir. İki uygulama arasındaki korelasyon yalnızca paralel ölçmelerde güvenirliğe eşittir.', c: 'Y14' },
      ],
      kontrol: [
        { soru: 'İki paralel formda s_X² = 100, r = 0,84. σ̂_E², ÖSH ve X = 70 için %68 bandı?', yanit: '16; 4; 66-74. Bant, hata varyansının puan düzeyine bağlı olmadığı varsayımıyla ve tekrarlanan ölçmeler üzerinden yorumlanır.', anahtar: 'A15.54', sayi: 16 },
      ],
    },
    {
      id: 'm6', kisa: 'Tekrar tasarımcısı', baslik: 'M6. Tekrar tasarımcısı: her yöntem "aynı ölçmeyi tekrarlamanın" farklı bir tanımıdır', dakika: 12,
      kazanimlar: [
        'Test-tekrar test, eşdeğer formlar ve iç tutarlılığın hangi kaynakları hata saydığını karşılaştırır (S1, S2; Y7).',
        'Bir hata kaynağının (ör. baş ağrısı) hangi katsayıda hata, hangisinde gerçek puan sayılacağını belirler (S2).',
      ],
      giris: 'İki ölçme arasında neyin değiştiğini seç: zaman, form ya da ikisi. Tablo, hangi kaynakların gerçek puana, hangilerinin hataya katıldığını yeniden boyar.',
      formuller: ['m6.rho_tekrar', 'm6.rho_esdeger', 'm6.rho_gecikmeli_esdeger'],
      gorulmesi: [
        { t: 'Aynı öğrenciler farklı katsayılar üretir: kararlılık katsayısı forma özgü hatayı görmez, eşdeğerlik katsayısı güne özgü hatayı görmez; yalnızca gecikmeli eşdeğer formlar ikisini de hata sayar ve genellikle en düşük değeri verir.', c: 'C.3' },
        { t: 'Bütün güvenirlik katsayıları aynı şeyi kestirmez; farklı kaynakları hata sayarlar ve birbirinin yerine kullanılamazlar.', c: 'Y7' },
      ],
      yontemler: [
        { ad: 'Test-tekrar test (kararlılık katsayısı)', veri: 'Aynı form, iki gün', hesap: 'İki uygulama arasındaki r', hata: 'Geçici durum (gün)', varsayim: 'Arada gerçek değişim ve bellek etkisi yok', tuzak: 'Gerçek değişim katsayıyı düşürür, bellek yükseltir.' },
        { ad: 'Eşdeğer formlar (eşdeğerlik katsayısı)', veri: 'İki form, bir gün', hesap: 'İki form arasındaki r', hata: 'İçerik örneklemesi (madde)', varsayim: 'Formların paralel olduğu varsayılır', tuzak: 'Korelasyon yalnızca paralel ölçmelerde güvenirliğe eşittir.' },
        { ad: 'Gecikmeli eşdeğer formlar', veri: 'İki form, iki gün', hesap: 'r', hata: 'Hem gün hem madde', varsayim: 'Paralel formlar', tuzak: 'Genellikle en düşük değeri verir; bu bir kusur değil, daha çok kaynağı hata saymasıdır.' },
        { ad: 'İç tutarlılık (α, yarıya bölme)', veri: 'Tek oturum', hesap: 'Madde varyansları ve toplam varyans', hata: 'Maddeye özgü ve rastgele', varsayim: 'Özünde tau eşdeğer parçalar, ilişkisiz hatalar', tuzak: 'Hız testlerinde yarıya bölme ve α şişer; ayrı zamanlanmış yarılar veya test-tekrar test kullanılır.' },
      ],
      kontrol: [
        { soru: 'Bir öğrencinin test günü başı ağrıyordu. Bu test-tekrar test için hata mı? Aynı oturumdan hesaplanan α için?', yanit: 'Test-tekrar test için hatadır. α için gerçek puana karışır; bu yüzden α, günden güne genellemek istediğimiz güvenirliği fazla kestirir.', anahtar: 'A15.57' },
      ],
    },
    {
      id: 'm7', kisa: 'Hesap Tezgâhı', baslik: 'M7. Hesap Tezgâhı: r ve iç tutarlılık', dakika: 15,
      kazanimlar: [
        'Pearson r, yarıya bölme (Spearman-Brown, Rulon), KR-20 ve α\'yı elle hesaplar (S1; Y15).',
        'Test uzunluğunun ve zayıf bir maddenin α üzerindeki etkisini açıklar (S1; Y10, Y11).',
      ],
      giris: 'Yöntemlerin adlarını biliyorsun; burada onları sütun sütun hesaplıyoruz. Sütunlar el hesabının sırasını izler: ham puan, sapma, kare veya çarpım, toplam, formül.',
      formuller: ['m7.r_sapma', 'm7.alpha', 'm7.kr20', 'm7.sb', 'm7.sb_yarilar', 'm7.flanagan_rulon', 'm7.rulon', 'm7.osh_orneklem'],
      uzmanFormuller: ['m7.sapma', 'm7.sb_carpan', 'm7.rulon_fark', 'm7.fr_ortalama_k_tek', 'm7.toplam_varyans_n', 'm7.kr20_pq_duzeltmesi', 'm7.kr21', 'm7.madde_varyansi_egrisi', 'm7.alpha_madde_silinirse', 'm7.duzeltilmis_madde_toplam_r', 'm7.max_rphi', 'm7.max_rphi_kosulu'],
      gorulmesi: [
        { t: 'Farklı bölmeler farklı sonuç verir; tek-çift bölme yalnızca bir bölmedir. k çiftken tüm eşit bölmelerin Flanagan-Rulon ortalaması α\'ya eşittir, Spearman-Brown ortalaması eşit değildir.', c: 'D.2' },
        { t: 'Madde varyansları toplamı ile toplam puan varyansı arasındaki fark güvenirliğin kaynağıdır: bu fark, maddeler arası kovaryanslardan gelir.', c: 'M7-Görülmesi gereken' },
        { t: 'Madde eklemek güvenirliği her zaman artırmaz: Spearman-Brown artışı yalnızca eklenen maddeler paralelse doğru yordar; yapıyla zayıf ilişkili bir madde α\'yı düşürebilir (Sabit Veri A\'ya 5. madde eklenince α 0,80\'den 0,68\'e).', c: 'Y10' },
        { t: 'Örneklem α\'sı negatif olabilir ve yarıya bölme değeri seçilen bölmeye bağlıdır.', c: 'Y15' },
      ],
      kontrol: [
        { soru: 'Yarı test korelasyonu 0,60 ise tam test?', yanit: '0,75.', anahtar: 'A15.60', sayi: 0.75 },
        { soru: '0,75\'ten test üç katına çıkarılırsa?', yanit: '0,90.', anahtar: 'A15.61', sayi: 0.9 },
        { soru: '0,60\'tan 0,80\'e çıkmak için uzunluk çarpanı?', yanit: '8/3 ≈ 2,67 (eklenen parçaların paralel olduğu varsayımıyla).', anahtar: 'A15.62', sayi: 8 / 3 },
      ],
    },
    {
      id: 'm8', kisa: 'Matris görünümü', baslik: 'M8. Matris görünümü', dakika: 13,
      kazanimlar: [
        'Toplam puan varyansını kovaryans matrisinin hücre toplamı olarak yazar ve α\'daki k/(k−1) çarpanını köşegen doldurma ile açıklar (S1, S3).',
        'α\'nın ω\'nın altında veya üstünde kaldığı koşulları ve α\'nın tek boyutluluk göstergesi olmadığını açıklar (Y5, Y6).',
      ],
      giris: 'Toplam puanın varyansı, kovaryans matrisinin bütün hücrelerinin toplamıdır. Köşegen dışı hücreler iki farklı maddenin paylaştığını, yani gerçek puanı taşır. Köşegen hücrelerin ne kadarının gerçek olduğunu göremeyiz; α bu görünmeyen kısmı ortalama köşegen dışı değerle doldurur.',
      formuller: ['m8.toplam_varyans', 'm8.alpha', 'm8.turetme_ortalama_kovaryans', 'm8.turetme_gercek_varyans', 'm8.turetme_alpha', 'm8.omega', 'm8.alpha_yukler'],
      uzmanFormuller: ['m8.sigma_ayrisimi', 'm8.hata_matrisi', 'm8.tek_faktor', 'm8.omega_paydasi_iliskisiz', 'm8.yuk_esitsizligi', 'm8.alpha_std', 'm8.l2', 'm8.iki_blok_orani', 'm8.psi_varsayilan', 'm8.psi_siniri', 'icerik.a5_paralel', 'icerik.a5_ozunde_tau_esdeger', 'icerik.a5_konjenerik'],
      gorulmesi: [
        { t: 'k/(k−1) çarpanı, k köşegen hücresinin görünmeyen gerçek kısmını kestirmek için k(k−1) köşegen dışı hücrenin ortalanmasından gelir.', c: 'M8-Görülmesi gereken' },
        { t: 'Hatalar ilişkisizken popülasyon α\'sı güvenirliğin alt sınırıdır; eşit olmayan yükler α\'yı ω\'nın altına düşürür ve α = ρ ancak özünde tau eşdeğerlikte olur.', c: 'D.1' },
        { t: 'Diğer koşullar sabitken pozitif hata kovaryansları α\'yı yükseltir, ω\'yı düşürür; yükler eşitse α ω\'yı aşabilir (0,7712 > 0,6588), eşit değilse aşmayabilir (0,6087 < 0,6576). Negatif hata kovaryansı α\'yı düşürür (λ = 0,625 × 4: α 0,7194\'ten 0,6975\'e).', c: 'B.12' },
        { t: 'Birbiriyle ilişkisiz iki blokta bile α sıfırdan uzaktır ve madde sayısıyla yükselir (6 maddede 0,5939, 12 maddede 0,7747). Yüksek α testin tek boyutlu olduğunu göstermez.', c: 'Y6' },
      ],
      kontrol: [
        { soru: 'Üç maddenin varyansları 4, 5, 6 ve bütün kovaryanslar 2 ise s_Y² ve α?', yanit: '27; 0,667.', anahtar: 'A15.63', sayi: 27 },
      ],
    },
    {
      id: 'm9', kisa: 'ANOVA ve GK', baslik: 'M9. Varyans analizi, Hoyt ve GK\'ya ön bakış', dakika: 15,
      kazanimlar: [
        'Kişi × madde verisinden ANOVA tablosunu kurar, Hoyt katsayısını hesaplar ve α\'ya eşitliğini gösterir (S1, S3).',
        'Bağıl ve mutlak karar için 𝔼ρ² ile Φ\'yi ayırt eder ve madde veya puanlayıcı güçlüğünün hangisine girdiğini açıklar (S2).',
      ],
      giris: 'Katman soyma: Sabit Veri A tablosu, hücre hücre toplandığında aslını veren dört tabloya ayrılır: genel ortalama, kişi etkisi, madde etkisi ve artık. Her tablonun karelerini topla; ANOVA tablosu satır satır kurulur.',
      formuller: ['m9.model', 'm9.kt_ayrisimi', 'm9.kt_kisi', 'm9.kt_madde', 'm9.kt_artik', 'm9.hoyt', 'm9.kanit_alpha_hoyt', 'm9.erho2', 'm9.phi'],
      uzmanFormuller: ['m9.sd_kisi', 'm9.sd_madde', 'm9.sd_artik', 'm9.kanit_toplam_varyans', 'm9.kanit_madde_varyanslari', 'm9.beklenen_ko_kisi', 'm9.beklenen_ko_madde', 'm9.beklenen_ko_artik', 'm9.bilesen_kisi', 'm9.bilesen_madde', 'm9.bilesen_artik', 'm9.phi_lambda', 'm9.phi_en_kucuk', 'm9.capraz_bagil_hata', 'm9.capraz_mutlak_hata', 'm9.icice_hata', 'm9.icice_bilesen', 'm9.icc_c_k', 'm9.icc_a_k_tam', 'm9.icc_c_1_tam', 'm9.icice_tek_yonlu_not'],
      ucYol: ['m9.uc_yol_matris', 'm9.uc_yol_anova', 'm9.uc_yol_katsayi', 'm9.uc_yol_kosegen'],
      gorulmesi: [
        { t: 'Madde güçlük farkları her öğrenci için aynıdır; öğrencileri sıralarken sabit hata gibi davranır ve Hoyt\'a, α\'ya, 𝔼ρ²\'ye girmez; sabit bir kesme puanında önemli olan Φ\'ye girer.', c: 'B.10' },
        { t: 'Hoyt tam olarak α\'dır (eksiksiz veri ve tutarlı payda koşuluyla). K çalışması eğrisi Spearman-Brown eğrisinin aynısıdır.', c: 'D.3, D.4' },
        { t: 'İç içe desende puanlayıcı katılık farkları bağıl hataya dönüşür. p × i artığı gerçek kişi × madde etkileşimini tesadüfi hatadan ayıramaz; α ikisini de hata sayar, çünkü tekrarları yeni maddelerdir.', c: 'B.10' },
      ],
      kontrol: [
        { soru: 'KO_p = 10, KO_art = 2 ise Hoyt?', yanit: '0,80.', anahtar: 'A15.65', sayi: 0.8 },
        { soru: '70 puanda geçti/kaldı kararı için hangi katsayı uygundur, neden?', yanit: 'Mutlak karar için Φ; kesme puanına özgü sürümü Φ(λ)\'dır ve Φ, Φ(λ)\'nın en küçük değeridir. Madde güçlüğündeki kaymalar mutlak puan düzeyini değiştirir.', anahtar: 'A15.66' },
      ],
    },
    {
      id: 'm10', kisa: 'Yanılgı denetimi', baslik: 'M10. Kavram yanılgısı denetimi', dakika: 15,
      kazanimlar: ['Y1-Y16 yanılgılarını tanır ve doğru ifadeyi seçer.'],
      giris: 'Her ifade için doğru olanı seç. Geri bildirim nedenini açıklar ve ilgili modüle götürür. Yanıtların yalnızca bu tarayıcıda kalır. Bu maddeler bir araştırma ölçme aracı değildir.',
      formuller: [], gorulmesi: [], kontrol: [],
    },
  ];

  // TGA kartları: her biri bir ön ayar çiftine (önce/sonra) bağlıdır; sonuç RelCore ile hesaplanır.
  const TGA = [
    { id: 'tga.m3.turdes', module: 'm3', onceki: 'm3.varsayilan', preset: 'm3.turdes', q: 'm3.rho', soru: 'Aynı test çok türdeş bir sınıfa (σ_T 8\'den 4\'e) uygulanırsa güvenirlik?', dogru: 'azalir', satir: 'G.9',
      gerekceler: [{ id: 'g1', t: 'Hata aynı kalırken gerçek farklar azalır; oran küçülür.', c: 'Y1', dogru: true }, { id: 'g2', t: 'Güvenirlik testin özelliğidir, değişmez.', c: 'Y1' }, { id: 'g3', t: 'Türdeş sınıfta hata azalır, güvenirlik artar.', c: 'Y1' }] },
    { id: 'tga.m4.sabit', module: 'm4', onceki: 'm4.varsayilan', preset: 'm4.sabit', q: 'm4.rho', ek: 'm4.ortalama', soru: 'Aynı öğretmen iki uygulamada da her kâğıda 5 puan fazla veriyor. Güvenirlik?', dogru: 'degismez', satir: 'G.3',
      gerekceler: [{ id: 'g1', t: 'Sabit, sapmalarda birbirini götürür; varyans ve kovaryans aynı kalır. Bedel ortalamaya ve kesme kararlarına yansır.', c: 'B.5', dogru: true }, { id: 'g2', t: 'Sabit hata düzeltilebilir olduğu için güvenirliği etkilemez.', c: 'Y16' }, { id: 'g3', t: 'Sistematik hata güvenirliği her zaman düşürür.', c: 'Y2' }] },
    { id: 'tga.m4.orantili', module: 'm4', onceki: 'm4.varsayilan', preset: 'm4.orantili', q: 'm4.rho', ek: 'm4.osh', soru: 'Her puan %10 fazla sayılıyor (X* = 1,1X). Güvenirlik?', dogru: 'degismez', satir: 'G.4',
      gerekceler: [{ id: 'g1', t: 'Ortak doğrusal dönüşüm oranları değiştirmez; ÖSH 1,1 katına çıkar.', c: 'B.0', dogru: true }, { id: 'g2', t: 'Orantılı hata yüksek puanlıları daha çok etkilediği için güvenirliği düşürür.', c: 'Y2' }, { id: 'g3', t: 'ÖSH de aynı kalır.', c: 'B.0' }] },
    { id: 'tga.m4.kararli', module: 'm4', onceki: 'm4.varsayilan', preset: 'm4.kararli', q: 'm4.rho', ek: 'm4.rho_xeta', soru: 'Puanlayıcı iki ölçmede de düzgün el yazısına puan ekliyor (yapıyla ilişkisiz, kararlı). Güvenirlik?', dogru: 'artar', satir: 'G.5',
      gerekceler: [{ id: 'g1', t: 'Her tekrarda aynı kalan yanlılık gerçek puana katılır; güvenirlik yükselir, yapıyla korelasyon düşer.', c: 'B.1', dogru: true }, { id: 'g2', t: 'Sistematik hata güvenirliği etkilemez.', c: 'Y2' }, { id: 'g3', t: 'Güvenilir test geçerlidir.', c: 'Y13' }] },
    { id: 'tga.m4.degisen', module: 'm4', onceki: 'm4.varsayilan', preset: 'm4.degisen', q: 'm4.rho', soru: 'Her uygulamada farklı öğrencilere yumuşak davranan farklı puanlayıcılar var. Güvenirlik?', dogru: 'azalir', satir: 'G.6',
      gerekceler: [{ id: 'g1', t: 'Tekrardan tekrara değişen yanlılık bu tasarım için tesadüfi hatadır.', c: 'B.3', dogru: true }, { id: 'g2', t: 'Yanlılık sistematik olduğu için güvenirliği etkilemez.', c: 'Y2' }] },
    { id: 'tga.m4.tesadufi', module: 'm4', onceki: 'm4.varsayilan', preset: 'm4.tesadufi', q: 'm4.rho', ek: 'm4.rho_xeta', soru: 'Tesadüfi hata artıyor (σ_E² 20\'den 40\'a). Güvenirlik?', dogru: 'azalir', satir: 'G.2',
      gerekceler: [{ id: 'g1', t: 'Hata gözlenen varyansı şişirir; oran küçülür ve korelasyonlar zayıflar.', c: 'Y3', dogru: true }, { id: 'g2', t: 'Tesadüfi hatalar birbirini götürür, önemsizdir.', c: 'Y3' }] },
    { id: 'tga.m4.altgrup', module: 'm4', onceki: 'm4.varsayilan', preset: 'm4.altgrup', q: 'm4.rho', ek: 'm4.grup_ici_rho', soru: '(Uzman) Bir alt gruba kararlı olarak puan ekleniyor. Havuzlanmış güvenirlik?', dogru: 'artar', satir: 'G.7', uzman: true,
      gerekceler: [{ id: 'g1', t: 'Alt grup kayması havuzlanmış gerçek varyansa katılır; grup içi güvenirlik değişmez. Bu bir adillik ve ölçme değişmezliği sorunudur.', c: 'B.11', dogru: true }, { id: 'g2', t: 'Güvenilir test geçerlidir.', c: 'Y13' }] },
    { id: 'tga.m4.tavan', module: 'm4', onceki: 'm4.tavan_once', preset: 'm4.tavan', q: 'm4.r12', soru: '(Uzman) Puanlar 100\'de kesiliyor ve sınıf tavana yakın. İki ölçme arasındaki korelasyon?', dogru: 'azalir', satir: 'G.10', uzman: true,
      gerekceler: [{ id: 'g1', t: 'Tavan, eklenen puanın herkese aynı olmasını bozar; doğrusal olmayan dönüşüm genellikle güvenirliği düşürür.', c: 'B.8', dogru: true }, { id: 'g2', t: 'Sabit ekleme her zaman güvenirliği korur.', c: 'Y16' }] },
    { id: 'tga.m6.k', module: 'm6', onceki: 'm6.varsayilan', preset: 'm6.k20', q: 'm6.alfa', soru: 'Madde sayısı 10\'dan 20\'ye çıkarsa (paralel maddeler) tek oturum α?', dogru: 'artar', satir: 'G.8',
      gerekceler: [{ id: 'g1', t: 'Maddeye özgü sapmalar ortalamada küçülür; madde ortalaması ölçeğinde hata varyansı azalır.', c: 'Y10', dogru: true }, { id: 'g2', t: 'Madde sayısı güvenirliği etkilemez.', c: 'Y10' }] },
    { id: 'tga.m5.bellek', module: 'm5', onceki: 'm5.sim', preset: 'm5.bellek', q: 'm5.r', soru: 'İki uygulama arasında öğrenciler ilk yanıtlarını hatırlıyor (hatalar ilişkili). Kestirilen güvenirlik?', dogru: 'artar', satir: 'G.11',
      gerekceler: [{ id: 'g1', t: 'İlişkili hatalar kovaryansı şişirir; güvenirlik fazla kestirilir.', c: 'Y14', dogru: true }, { id: 'g2', t: 'Bellek gerçek puanı artırır, kestirim doğrudur.', c: 'Y14' }] },
    { id: 'tga.m5.degisim', module: 'm5', onceki: 'm5.sim', preset: 'm5.degisim', q: 'm5.r', soru: 'İki uygulama arasında öğrenciler farklı hızlarda öğreniyor. Kestirilen güvenirlik?', dogru: 'azalir', satir: 'G.12',
      gerekceler: [{ id: 'g1', t: 'Farklı gerçek değişim korelasyonu düşürür; güvenirlik az kestirilir.', c: 'Y14', dogru: true }, { id: 'g2', t: 'Öğrenme hatayı azaltır, güvenirlik artar.', c: 'Y14' }] },
    { id: 'tga.m4.ikinci', module: 'm4', onceki: 'm4.varsayilan', preset: 'm4.ikinci', q: 'm4.icc_a1', ek: 'm4.r12', soru: '(Uzman) Sabit kayma yalnızca ikinci ölçmede. Mutlak uyum ICC(A,1)?', dogru: 'azalir', satir: 'G.13', uzman: true,
      gerekceler: [{ id: 'g1', t: 'r ve bağıl katsayılar değişmez; mutlak uyum indeksleri düşer.', c: 'B.9', dogru: true }, { id: 'g2', t: 'Sabit hata hiçbir katsayıyı etkilemez.', c: 'Y2' }] },
    { id: 'tga.m3.hata', module: 'm3', onceki: 'm3.varsayilan', preset: 'm3.hata', q: 'm3.rho', soru: 'Ölçme daha gürültülü hale geliyor (σ_E 4\'ten 8\'e). Güvenirlik?', dogru: 'azalir', satir: 'G.2b',
      gerekceler: [{ id: 'g1', t: 'Hata varyansı paydayı büyütür.', c: 'A.4', dogru: true }, { id: 'g2', t: 'Gürültü ortalamada kaybolur.', c: 'Y3' }] },
    { id: 'tga.m3.gercek', module: 'm3', onceki: 'm3.varsayilan', preset: 'm3.gercek', q: 'm3.rho', soru: 'Öğrenciler gerçekte daha farklı (σ_T 8\'den 12\'ye). Güvenirlik?', dogru: 'artar', satir: 'G.1',
      gerekceler: [{ id: 'g1', t: 'Gerçek varyans payı büyür; hata aynı kalır.', c: 'A.4', dogru: true }, { id: 'g2', t: 'Güvenirlik testin sabit bir özelliğidir.', c: 'Y1' }] },
  ];

  // Etki haritası (SPEC G tablosu). Sütunlar: Ortalama | Gözlenen varyans | Güvenirlik | ÖSH | Sabit kesme puanında kararlar | ρ_Xη
  const ETKI = {
    sutunlar: ['Ortalama', 'Gözlenen varyans', 'Güvenirlik', 'ÖSH', 'Kesme puanında kararlar', 'Yapıyla korelasyon ρ_Xη (yalnızca simülasyonda)'],
    satirlar: [
      { id: 'G.1', ad: 'Gerçek farklar artar', hucre: ['=', '↑', '↑', '=', '~ kesmenin ortalamaya göre yerine bağlı', '↑'], modul: 'm3', tga: 'tga.m3.gercek' },
      { id: 'G.2', ad: 'Tesadüfi hata artar', hucre: ['=', '↑', '↓', '↑', '~', '↓'], modul: 'm4', tga: 'tga.m4.tesadufi' },
      { id: 'G.3', ad: 'Sabit hata c > 0, herkese ve her tekrarda', hucre: ['↑', '=', '=', '=', 'değişir', '='], modul: 'm4', tga: 'tga.m4.sabit' },
      { id: 'G.4', ad: 'Kurala bağlı hata X* = wX, w > 1', hucre: ['↑', '↑', '=', '↑', 'değişir', '='], modul: 'm4', tga: 'tga.m4.orantili' },
      { id: 'G.5', ad: 'Kişiye özgü kararlı yanlılık B (B ⊥ η)', hucre: ['=', '↑', '↑', '=', '~', '↓'], modul: 'm4', tga: 'tga.m4.kararli' },
      { id: 'G.6', ad: 'Aynı yanlılık tekrardan tekrara değişirse', hucre: ['=', '↑', '↓', '↑', '~', '↓'], modul: 'm4', tga: 'tga.m4.degisen' },
      { id: 'G.7', ad: 'Alt gruba özgü kararlı kayma γ > 0 (g ⊥ η)', hucre: ['↑', '↑', 'havuzlanmış ↑, grup içi =', '=', 'değişir', '↓ (grup farkı γ kadar yanlı)'], modul: 'm4', tga: 'tga.m4.altgrup' },
      { id: 'G.8', ad: 'Madde sayısı artar (paralel maddeler, madde ortalaması ölçeği)', hucre: ['=', '↓', '↑', '↓', '~', '↑'], modul: 'm6', tga: 'tga.m6.k' },
      { id: 'G.9', ad: 'Grup türdeşleşir (σ_T ↓, hata aynı)', hucre: ['=', '↓', '↓', '=', '~', '↓'], modul: 'm3', tga: 'tga.m3.turdes' },
      { id: 'G.10', ad: 'Sabit eklenirken tavan etkisi', hucre: ['↑ (c\'den az)', 'genellikle ↓', 'genellikle ↓ (Sabit Veri A: 0,80 → 0,7427)', '~', 'değişir', 'genellikle ↓'], modul: 'm4', tga: 'tga.m4.tavan' },
      { id: 'G.11', ad: 'Bellek etkisi (test-tekrar test, ilişkili hatalar)', hucre: ['=', '=', 'kestirim ↑ (fazla kestirir)', '=', '=', '='], modul: 'm5', tga: 'tga.m5.bellek' },
      { id: 'G.12', ad: 'Farklı gerçek değişim (test-tekrar test)', hucre: ['', '', 'kestirim ↓ (az kestirir)', '', '', ''], modul: 'm5', tga: 'tga.m5.degisim' },
      { id: 'G.13', ad: 'Sabit kayma yalnızca ikinci ölçmede', hucre: ['ikinci ölçmenin ortalaması ↑', '=', 'r =, mutlak uyum ↓', '=', 'değişir', '='], modul: 'm4', tga: 'tga.m4.ikinci' },
    ],
  };

  // Hata türleri tablosu (M4 açılış kartı)
  const HATA_TABLOSU = {
    basliklar: ['Ders notlarındaki ad ve tipik örnek', 'Laboratuvardaki karşılığı', 'Güvenirliğe etkisi', 'Ortalamaya ve mutlak kararlara etkisi', 'Yapıyla ilişkiye (bir geçerlik kanıtına) etkisi'],
    satirlar: [
      ['Sabit hata: her birime aynı miktar (öğretmenin her kâğıda 5 puan fazla vermesi; puanlama yazılımının herkesten 4 puan düşmesi)', 'c', 'değişmez', 'ortalama c kadar kayar; kesme puanındaki kararlar değişir', 'ρ_Xη değişmez; mutlak yorum ("70 aldı") ise yanlıştır'],
      ['Sistematik hata; ders notlarında çoğunlukla "belli bir kurala göre", çoğu kez orantılı (her kilogramda 100 g eksik tartan terazi; her puanın %10 fazla sayılması)', 'X* = a + wX', 'değişmez; ÖSH |w| katına çıkar', 'ortalama ve kararlar değişir', 'ρ_Xη değişmez'],
      ['Ders notlarında ayrı adı yoktur: kişiye veya gruba özgü kararlı yanlılık (düzgün el yazısına hale etkisi; matematik testinde okuma yükü; bir gruba karşı katı puanlayıcı)', 'B_p, γg_p', 'değişir: çoğunlukla yükselir, yapıyla güçlü ters ilişkiliyse düşer', 'grup ortalamaları yanlı olur', 'düşer'],
      ['Tesadüfi hata', 'E', 'düşer', 'grup ortalamasında kaybolur; bireysel kararlar tutarsızlaşır', 'düşer'],
    ],
    alt: 'Tekrardan tekrara değişen her yanlılık, adı ne olursa olsun, o tekrar tasarımı için tesadüfi hatadır.',
  };

  // M6 kaynak-rol tablosu: hangi kaynak hangi katsayıda gerçek, hangisinde hata
  const SOURCE_ROLES = {
    gecici: { ad: 'Geçici durum (baş ağrısı, yorgunluk; gün)', tekrar: 'hata', esdeger: 'gercek', gecikmeli: 'hata', alfa: 'gercek' },
    madde: { ad: 'Maddeye özgü (içerik örneklemesi)', tekrar: 'gercek', esdeger: 'hata', gecikmeli: 'hata', alfa: 'hata' },
    rastgele: { ad: 'Rastgele (anlık dikkat, tahmin)', tekrar: 'hata', esdeger: 'hata', gecikmeli: 'hata', alfa: 'hata' },
    hiz: { ad: 'Hız ve ortak yöntem', tekrar: 'gercek', esdeger: 'gercek', gecikmeli: 'gercek', alfa: 'gercek' },
  };

  // M10 biçimlendirici maddeler (E bölümü)
  const YANILGILAR = [
    { id: 'Y1', yanlis: 'Güvenirlik testin özelliğidir.', dogru: 'Güvenirlik, belirli bir tekrar tasarımı altında belirli bir popülasyondaki puanların özelliğidir.', modul: 'm3' },
    { id: 'Y2', yanlis: 'Sistematik hata güvenirliği hiç etkilemez, bu yüzden zararsızdır.', dogru: 'Sabit ve ortak doğrusal hatalar güvenirliği değiştirmez ama ortalamaya ve mutlak kararlara zarar verir; kişiye özgü kararlı yanlılık güvenirliği değiştirir ve yapıyla ilişkiyi zayıflatabilir.', modul: 'm4' },
    { id: 'Y3', yanlis: 'Tesadüfi hata birbirini götürür, önemsizdir.', dogru: 'Çok kişide grup ortalamasında ortalanır; bireysel puanda götürülmez, gözlenen varyansı şişirir ve korelasyonları zayıflatır.', modul: 'm1' },
    { id: 'Y4', yanlis: 'Her kişinin hata puanını hesaplayabiliriz.', dogru: 'Bireysel hata gözlenemez; hesaplanan X − T̂ değerleri artıklardır. Yalnızca hata varyansı, en az iki tekrardan kestirilebilir.', modul: 'm5' },
    { id: 'Y5', yanlis: 'α güvenirliğin kendisidir.', dogru: 'Hatalar ilişkisizse popülasyon α\'sı güvenirliğin alt sınırıdır; α = ρ ancak özünde tau eşdeğerlikte olur. İlişkili hatalarla abartabilir.', modul: 'm8' },
    { id: 'Y6', yanlis: 'Yüksek α testin tek boyutlu olduğunu gösterir.', dogru: 'Göstermez; ilişkisiz iki blokta bile α yüksek olabilir.', modul: 'm8' },
    { id: 'Y7', yanlis: 'Bütün güvenirlik katsayıları aynı şeyi kestirir.', dogru: 'Farklı kaynakları hata sayarlar ve birbirinin yerine kullanılamazlar.', modul: 'm6' },
    { id: 'Y8', yanlis: 'ρ = 0,80, her kişinin puanının %80\'i gerçektir demektir.', dogru: 'Bu popülasyonda gözlenen varyansın %80\'i gerçek varyanstır; bireyler hakkında bir ifade değildir.', modul: 'm3' },
    { id: 'Y9', yanlis: 'ÖSH herkes için aynıdır ve X ± 1,96 ÖSH gerçek puanı %95 olasılıkla içerir.', dogru: 'ÖSH bir popülasyon ortalamasıdır ve puan düzeyine göre değişebilir; %95, varsayımlar altında tekrarlanan ölçmelerdeki kapsama oranıdır.', modul: 'm5' },
    { id: 'Y10', yanlis: 'Madde eklemek güvenirliği her zaman artırır.', dogru: 'Spearman-Brown artışı ancak eklenen maddeler paralelse doğru yordar; yapıyla zayıf ilişkili maddeler α\'yı düşürebilir.', modul: 'm7' },
    { id: 'Y11', yanlis: 'Daha yüksek her zaman daha iyidir; α ≥ 0,95 idealdir.', dogru: 'Çok yüksek α fazlalığa ve daralmış yapıya işaret edebilir (zayıflama paradoksu); gereken düzeyi amaç belirler.', modul: 'm7' },
    { id: 'Y12', yanlis: 'Nunnally 0,70\'i evrensel eşik olarak koydu.', dogru: 'Gereken düzeyi kullanım amacına bağladı (Lance, Butts ve Michels, 2006).', modul: 'm7' },
    { id: 'Y13', yanlis: 'Güvenilir test geçerlidir.', dogru: 'Güvenirlik gerekli ama yeterli değildir; kararlı, yapıyla ilgisiz varyans güvenirliği yükseltir, yapıyla korelasyonu düşürür.', modul: 'm4' },
    { id: 'Y14', yanlis: 'İki uygulama arasındaki korelasyon her zaman güvenirliktir.', dogru: 'Yalnızca paralel ölçmelerde; gerçek değişim düşürür, bellek yükseltir.', modul: 'm5' },
    { id: 'Y15', yanlis: 'α 0 ile 1 arasındadır ve yarıya bölme katsayısı tek bir sayıdır.', dogru: 'Örneklem α\'sı negatif olabilir; yarıya bölme değeri bölmeye bağlıdır.', modul: 'm7' },
    { id: 'Y16', yanlis: 'Sabit hata düzeltilebilir olduğu için güvenirliği etkilemez.', dogru: 'Nedeni düzeltilebilirlik değildir; varyans ve kovaryans yalnızca ortalamadan uzaklıklara bakar. Kaynağı bilinmeyen bir sabit de güvenirliği değiştirmez.', modul: 'm4' },
  ];

  const SOZLUK = [
    ['güvenirlik', 'reliability', 'Bu puanların bu gruptaki tutarlılığı; gerçek varyansın gözlenen varyansa oranı.'],
    ['geçerlik', 'validity', 'Puan yorumlarının kanıtla desteklenme derecesi; bir katsayı değildir.'],
    ['gözlenen puan (X)', 'observed score', 'Ölçmede elde edilen puan.'],
    ['gerçek puan (T)', 'true score', 'Sonsuz tekrarın ortalaması (KTK tanımı).'],
    ['hata puanı (E)', 'error score', 'X − T; bireyde gözlenemez.'],
    ['yapı puanı (η)', 'construct score', 'Ölçülmek istenen özelliğin düzeyi; yalnızca simülasyonda vardır.'],
    ['sabit hata', 'constant error', 'Herkese ve her tekrarda aynı eklenen miktar.'],
    ['kurala bağlı (orantılı) sistematik hata', 'proportional error', 'Herkese aynı kuralla uygulanan doğrusal dönüşüm.'],
    ['kararlı yanlılık', 'stable bias', 'Kişiye veya gruba özgü, tekrarlarda yinelenen sapma.'],
    ['tesadüfi (rastgele) hata', 'random error', 'Bu tekrar tasarımında yinelenmeyen her şey.'],
    ['sapma', 'deviation', 'Ortalamadan uzaklık (X − X̄). Hata kaynağı için "yanlılık", ortalamanın ötelenmesi için "kayma" kullanılır.'],
    ['popülasyon (evren)', 'population', 'Kişi evreni. GK\'daki "evren puanı" farklıdır: kabul edilebilir koşullar evreni üzerindeki ortalama puan.'],
    ['ölçmenin standart hatası (ÖSH)', 'standard error of measurement', 'Hata puanlarının standart sapması.'],
    ['test-tekrar test (kararlılık katsayısı)', 'test-retest (stability)', 'Aynı formun iki gün uygulanması.'],
    ['eşdeğer formlar yöntemi (eşdeğerlik katsayısı)', 'alternate forms (equivalence)', 'İki formun bir gün uygulanması; formların paralel olduğu varsayılır. Bazı Türkçe kaynaklar "eşdeğer ölçmeler"i tau eşdeğer anlamında kullanır.'],
    ['paralel ölçmeler', 'parallel measures', 'Aynı gerçek puan ve eşit hata varyansı; KTK\'nın kesin koşulu.'],
    ['özünde tau eşdeğer', 'essentially tau-equivalent', 'Gerçek puanlar yalnızca bir sabitle farklılaşır.'],
    ['konjenerik', 'congeneric', 'Gerçek puanlar doğrusal ilişkilidir; yükler farklı olabilir.'],
    ['iç tutarlılık', 'internal consistency', 'Tek oturumdaki maddeler arası tutarlılık.'],
    ['L₂ (Guttman λ₂)', 'Guttman lambda-2', 'Literatürde ve SPSS çıktısında λ₂ ("Lambda 2") yazılır; burada faktör yüküyle karışmasın diye L kullanılır.'],
    ['varyans bileşeni', 'variance component', 'Bir kaynağın evren düzeyindeki varyans payı.'],
    ['G çalışması ve K (karar) çalışması', 'G study, D study', 'Bileşenleri kestirme ve farklı desenler için katsayıları hesaplama.'],
    ['G katsayısı (𝔼ρ²)', 'generalizability coefficient', 'Bağıl kararlar için; literatürde Eρ² diye de yazılır.'],
    ['Φ katsayısı', 'dependability (index of dependability)', 'Mutlak kararlar için.'],
    ['sınıf içi korelasyon (ICC)', 'intraclass correlation', 'Tutarlılık (C) veya mutlak uyum (A) türleri.'],
    ['kestirim / yordama / tahmin', 'estimation / prediction / guess', 'Kestirim: veriden parametre değeri. Yordama: regresyonla öngörme. Tahmin: TGA kartındaki öngörün.'],
    ['türdeş', 'homogeneous', 'Yalnızca gruplar için kullanılır ("türdeş sınıf").'],
    ['Tahmin-Gözlem-Açıklama (TGA)', 'predict-observe-explain', 'Önce tahmin et, sonra gözle, sonra açıkla.'],
  ];

  const KAYNAKLAR = [
    'AERA, APA ve NCME (2014). Standards for educational and psychological testing.',
    'Baykul, Y. Eğitimde ve psikolojide ölçme: Klasik test teorisi ve uygulaması. Pegem Akademi.',
    'Brennan, R. L. (2001a). Generalizability theory. Springer.',
    'Brennan, R. L. (2001b). An essay on the history and future of reliability from the perspective of replications. Journal of Educational Measurement, 38(4), 295-317.',
    'Brennan, R. L. ve Kane, M. T. (1977). An index of dependability for mastery tests. JEM, 14(3), 277-289.',
    'Brown, W. (1910). Some experimental results in the correlation of mental abilities. British Journal of Psychology, 3, 296-322.',
    'Crocker, L. ve Algina, J. (1986). Introduction to classical and modern test theory.',
    'Cronbach, L. J. (1951). Coefficient alpha and the internal structure of tests. Psychometrika, 16(3), 297-334.',
    'Cronbach, L. J., Gleser, G. C., Nanda, H. ve Rajaratnam, N. (1972). The dependability of behavioral measurements.',
    'Dudek, F. J. (1979). The continuing misinterpretation of the standard error of measurement. Psychological Bulletin, 86(2), 335-337.',
    'Gulliksen, H. (1950). Theory of mental tests.',
    'Guttman, L. (1945). A basis for analyzing test-retest reliability. Psychometrika, 10(4), 255-282.',
    'Hoyt, C. (1941). Test reliability estimated by analysis of variance. Psychometrika, 6(3), 153-160.',
    'Kelley, T. L. (1927). Interpretation of educational measurements (künye doğrulanacak).',
    'Kuder, G. F. ve Richardson, M. W. (1937). The theory of the estimation of test reliability. Psychometrika, 2(3), 151-160.',
    'Lance, C. E., Butts, M. M. ve Michels, L. C. (2006). The sources of four commonly reported cutoff criteria. Organizational Research Methods, 9(2), 202-220.',
    'Loevinger, J. (1954). The attenuation paradox in test theory. Psychological Bulletin, 51, 493-504.',
    'Lord, F. M. (1952). The relation of the reliability of multiple-choice tests to the distribution of item difficulties. Psychometrika, 17, 181-194.',
    'Lord, F. M. ve Novick, M. R. (1968). Statistical theories of mental test scores.',
    'McDonald, R. P. (1999). Test theory: A unified treatment.',
    'McGraw, K. O. ve Wong, S. P. (1996). Forming inferences about some intraclass correlation coefficients. Psychological Methods, 1(1), 30-46.',
    'McNeish, D. (2018). Thanks coefficient alpha, we\'ll take it from here. Psychological Methods, 23(3), 412-433.',
    'Messick, S. (1989). Validity. Educational measurement (3. baskı), 13-103.',
    'Novick, M. R. ve Lewis, C. (1967). Coefficient alpha and the reliability of composite measurements. Psychometrika, 32(1), 1-13.',
    'Nunnally, J. C. (1978). Psychometric theory (2. baskı).',
    'Raykov, T. (2001). Bias of coefficient alpha for fixed congeneric measures with correlated errors. Applied Psychological Measurement, 25(1), 69-76.',
    'Rulon, P. J. (1939). A simplified procedure for determining the reliability of a test by split-halves. Harvard Educational Review, 9, 99-103.',
    'Schmidt, F. L., Le, H. ve Ilies, R. (2003). Beyond alpha. Psychological Methods, 8(2), 206-224.',
    'Shavelson, R. J. ve Webb, N. M. (1991). Generalizability theory: A primer.',
    'Shrout, P. E. ve Fleiss, J. L. (1979). Intraclass correlations: Uses in assessing rater reliability. Psychological Bulletin, 86(2), 420-428.',
    'Sijtsma, K. (2009). On the use, the misuse, and the very limited usefulness of Cronbach\'s alpha. Psychometrika, 74(1), 107-120.',
    'Spearman, C. (1904). The proof and measurement of association between two things. American Journal of Psychology, 15, 72-101.',
    'Spearman, C. (1910). Correlation calculated from faulty data. British Journal of Psychology, 3, 271-295.',
    'Thompson, B. ve Vacha-Haase, T. (2000). Psychometrics is datametrics: The test is not reliable. EPM, 60(2), 174-195.',
  ];

  // Kontrol soruları ve TGA sonuçlarının sayısal/kategorik yanıt anahtarları (A15)
  const ANSWER_KEYS = {
    'A15.1': 'esit', 'A15.2': 'degismez', 'A15.3': 1, 'A15.4': 'r<1', 'A15.5': 'degismez', 'A15.6': 'duser',
    'A15.7': 60, 'A15.8': [2, -2, 5, -5, 0], 'A15.9': 63, 'A15.10': [2, -2, 5, -5, 0],
    'A15.11': 0.80, 'A15.12': 0.50, 'A15.13': 4, 'A15.14': 4, 'A15.15': 'duser', 'A15.16': 'degismez',
    'A15.17': 'degismez', 'A15.18': 'degismez', 'A15.19': 'degismez', 'A15.20': 'ortalama+c', 'A15.21': 'degisir',
    'A15.22': 4 / 5, 'A15.23': 'degismez', 'A15.24': 2.2, 'A15.25': 13.2,
    'A15.26': 0.75, 'A15.27': Math.sqrt(0.75), 'A15.28': 0.80, 'A15.29': Math.sqrt(0.60), 'A15.30': Math.sqrt(0.80),
    'A15.31': 'duser', 'A15.32': 'duser', 'A15.33': 'duser', 'A15.34': 17 / 18, 'A15.35': 408 / 803, 'A15.36': 68 / Math.sqrt(5180),
    'A15.37': 'sifir_degil', 'A15.38': 2 / 7, 'A15.39': 'negatif', 'A15.40': 5 / 7, 'A15.41': 2 / 3, 'A15.42': 'gamma',
    'A15.43': 280 / 377, 'A15.44': 'degisir', 'A15.45': 76 / 91, 'A15.46': 10 / 11, 'A15.47': 2 / 7,
    'A15.48': 'degismez', 'A15.49': 'degismez', 'A15.50': -4, 'A15.51': 'degisir', 'A15.52': 'yukselir', 'A15.53': 'duser',
    'A15.54': 16, 'A15.55': 4, 'A15.56': [66, 74], 'A15.57': 'hata', 'A15.58': 'gercek', 'A15.59': 'fazla',
    'A15.60': 0.75, 'A15.61': 0.90, 'A15.62': 8 / 3, 'A15.63': 27, 'A15.64': 0.667, 'A15.65': 0.80, 'A15.66': 'phi', 'A15.67': 24 / 31,
  };

  const UI = {
    baslik: 'Güvenirlik Laboratuvarı',
    altbaslik: 'Klasik Test Kuramında güvenirlik: formüller, hesaplar ve ne neyi nasıl etkiliyor',
    gorunum: { real: 'Gerçek dünya', backstage: 'Perde arkası (simülasyon)' },
    gorunumAciklama: 'Gerçek dünyada yalnızca gözlenen puanlar X görünür. Perde arkasında simülasyonun bildiği T, E ve yapı puanı η da görünür.',
    sinifKodu: 'Sınıf kodu', yeniSinif: 'Yeni sınıf çek', uzmanModu: 'Uzman modu', payda: 'Payda', dahaFazla: 'Daha fazla basamak',
    neDegisti: 'Ne değişti, neden?', formulKarti: ['Sözle', 'Sembolle', 'Sayılarla'], terimler: 'Terimler',
    tabloyuGoster: 'Tabloyu göster', sonucuGoster: 'Sonucu göster', tahminin: 'Tahminin', sonuc: 'Sonuç',
    yonler: { artar: 'artar', azalir: 'azalır', degismez: 'değişmez' }, guven: ['emin değilim', 'emin', 'çok emin'],
    butce: 'Varyans bütçesi', butceKestirim: 'kestirim', ikinciOlcme: 'İkinci ölçmeyi ekle', ikinciGerek: 'Ayrıştırmak için ikinci bir ölçme gerekir.',
    etkiHaritasi: 'Etki haritası', sozluk: 'Sözlük', kaynaklar: 'Kaynaklar', kaynakNotu: 'Yayın öncesi künyeler doğrulanacaktır.',
    kontrol: 'Kontrol', yanitiGoster: 'Yanıtı göster', acemi: 'Acemi yolu', uzman: 'Uzman katmanı', gorulmesi: 'Görülmesi gereken',
    geçerlikNotu: 'Geçerlik bir katsayı değildir; puan yorumlarının kanıtla desteklenme derecesidir. Bu gösterge, yalnızca simülasyonda görülebilen bir kanıt türüdür.',
    perdeTGA: 'Şimdi perdeyi kapat. Yalnızca X\'i görseydin neyi bilebilirdin?',
    dilNotu: 'Bu sayfada "testin güvenirliği" yerine "bu puanların bu gruptaki güvenirliği" yazılır.',
  };

  const CONTENT = { formulas: F, terms: TERMS, modules: MODULES, tga: TGA, effectMap: ETKI, errorTable: HATA_TABLOSU, sourceRoles: SOURCE_ROLES, misconceptions: YANILGILAR, glossary: SOZLUK, references: KAYNAKLAR, answerKeys: ANSWER_KEYS, ui: UI };
  if (typeof module !== 'undefined' && module.exports) module.exports = CONTENT;
  root.RelContent = CONTENT;
})(typeof globalThis !== 'undefined' ? globalThis : this);
